#include "codegen.hpp"
#include <sstream>
#include <stdexcept>
#include <algorithm>

// ══════════════════════════════════════════════════════════
//  Constructor
// ══════════════════════════════════════════════════════════

CodeGenerator::CodeGenerator()
    : instrCount_(0), memOffset_(0) {
    // All registers free initially
    for (int i = 0; i < 8; i++)
        regFree_[i] = true;
}

// ══════════════════════════════════════════════════════════
//  Emit helpers
// ══════════════════════════════════════════════════════════

void CodeGenerator::emit(AsmOp op,
                          const std::string& dst,
                          const std::string& src1,
                          const std::string& src2,
                          const std::string& cmt,
                          int tid) {
    instrs_.emplace_back(++instrCount_, op,
                         dst, src1, src2, cmt, tid);
}

void CodeGenerator::emitComment(const std::string& text, int tid) {
    emit(AsmOp::COMMENT, "", "", "", text, tid);
}

// ══════════════════════════════════════════════════════════
//  Register allocator
// ══════════════════════════════════════════════════════════

Reg CodeGenerator::findFreeReg() {
    // R0 is the ABI return-value register. Keeping variables out of R0 avoids
    // recursive calls clobbering caller locals that are still needed.
    for (int i = 1; i < 8; i++) {
        if (regFree_[i])
            return static_cast<Reg>(i);
    }
    return Reg::NONE;
}

void CodeGenerator::spillReg(Reg r) {
    if (regUser_.count(r)) {
        std::string var = regUser_[r];
        // Spill to memory
        int offset = memOffset_++;
        memMap_[var] = offset;
        emit(AsmOp::STORE,
             "MEM[" + std::to_string(offset) + "]",
             regName(r), "", "spill " + var, 0);
        regMap_.erase(var);
        regUser_.erase(r);
        regFree_[static_cast<int>(r)] = true;
    }
}

Reg CodeGenerator::allocReg(const std::string& var) {
    // Already allocated?
    if (regMap_.count(var))
        return regMap_[var];

    Reg r = findFreeReg();

    // No free register — spill R7 (simple strategy)
    if (r == Reg::NONE) {
        r = Reg::R7;
        spillReg(r);
    }

    regMap_[var]              = r;
    regUser_[r]               = var;
    regFree_[static_cast<int>(r)] = false;
    return r;
}

Reg CodeGenerator::getReg(const std::string& var) {
    if (regMap_.count(var))
        return regMap_[var];
    // Not in register — load from memory
    Reg r = allocReg(var);
    if (memMap_.count(var)) {
        emit(AsmOp::LOAD, regName(r),
             "MEM[" + std::to_string(memMap_[var]) + "]",
             "", "reload " + var, 0);
    }
    return r;
}

void CodeGenerator::freeReg(const std::string& var) {
    if (regMap_.count(var)) {
        Reg r = regMap_[var];
        regFree_[static_cast<int>(r)] = true;
        regUser_.erase(r);
        regMap_.erase(var);
    }
}

void CodeGenerator::freeReg(Reg r) {
    if (regUser_.count(r)) {
        std::string var = regUser_[r];
        regMap_.erase(var);
        regUser_.erase(r);
    }
    regFree_[static_cast<int>(r)] = true;
}

// ── Load an operand into a register or return immediate ──
std::string CodeGenerator::loadOperand(const std::string& val,
                                        int tid) {
    if (val.empty()) return "";

    // Constant — return as immediate
    if (isConstant(val))
        return "#" + val;

    // Variable/temp — load into register
    Reg r = getReg(val);
    return regName(r);
}

bool CodeGenerator::isConstant(const std::string& val) const {
    if (val.empty()) return false;
    size_t start = (val[0] == '-') ? 1 : 0;
    if (start >= val.size()) return false;
    for (size_t i = start; i < val.size(); i++) {
        char c = val[i];
        if (!std::isdigit(c) && c != '.' && c != 'f' && c != 'F')
            return false;
    }
    return true;
}

// ══════════════════════════════════════════════════════════
//  Main entry
// ══════════════════════════════════════════════════════════

void CodeGenerator::generate(const std::vector<TACInstr>& optimized) {
    instrs_.clear();
    instrCount_ = 0;
    memOffset_  = 0;
    regMap_.clear();
    regUser_.clear();
    for (int i = 0; i < 8; i++) regFree_[i] = true;

    emitComment("Generated by Metamic Visual Compiler");
    emitComment("Target: Virtual Register Machine (VRM)");
    emitComment("Registers: R0-R7");

    for (const auto& t : optimized) {
        switch (t.op) {
            case TACOp::FUNC_BEGIN:  genFuncBegin(t);  break;
            case TACOp::FUNC_END:    genFuncEnd(t);    break;
            case TACOp::ASSIGN:
            case TACOp::COPY:        genAssign(t);     break;
            case TACOp::ADD: case TACOp::SUB:
            case TACOp::MUL: case TACOp::DIV:
            case TACOp::MOD:
            case TACOp::BIT_AND: case TACOp::BIT_OR:
            case TACOp::BIT_XOR:
            case TACOp::LSHIFT: case TACOp::RSHIFT:
            case TACOp::EQ:  case TACOp::NEQ:
            case TACOp::LT:  case TACOp::GT:
            case TACOp::LTE: case TACOp::GTE:
            case TACOp::AND: case TACOp::OR:
                genBinaryOp(t); break;
            case TACOp::NOT:
            case TACOp::BIT_NOT:     genUnaryOp(t);   break;
            case TACOp::JUMP:        genJump(t);       break;
            case TACOp::JUMP_IF:     genJumpIf(t);     break;
            case TACOp::JUMP_IFNOT:  genJumpIfNot(t);  break;
            case TACOp::LABEL:       genLabel(t);      break;
            case TACOp::CALL:        genCall(t);       break;
            case TACOp::RETURN:      genReturn(t);     break;
            case TACOp::PARAM:       genParam(t);      break;
            case TACOp::PRINT:       genPrint(t);      break;
            case TACOp::READ:        genRead(t);       break;
            case TACOp::NOP:
                emit(AsmOp::NOP, "", "", "", "", t.line);
                break;

            // Member / array access — emit MOV stubs so runtime stays consistent
            case TACOp::MEMBER_GET: {
                Reg r = allocReg(t.result);
                emitComment("member_get: " + t.toString(), t.line);
                emit(AsmOp::MOV, regName(r), "#0", "", t.result + " = " + t.arg1 + "." + t.arg2, t.line);
                break;
            }
            case TACOp::MEMBER_SET:
                emitComment("member_set: " + t.toString(), t.line);
                emit(AsmOp::NOP, "", "", "", t.arg1 + "." + t.arg2 + " = " + t.result, t.line);
                break;
            case TACOp::ARRAY_GET: {
                Reg r = allocReg(t.result);
                emitComment("array_get: " + t.toString(), t.line);
                emit(AsmOp::MOV, regName(r), "#0", "", t.result + " = " + t.arg1 + "[" + t.arg2 + "]", t.line);
                break;
            }
            case TACOp::ARRAY_SET:
                emitComment("array_set: " + t.toString(), t.line);
                emit(AsmOp::NOP, "", "", "", t.arg1 + "[" + t.arg2 + "] = " + t.result, t.line);
                break;
            case TACOp::ALLOC: {
                Reg r = allocReg(t.result);
                emitComment("alloc: " + t.toString(), t.line);
                emit(AsmOp::MOV, regName(r), "#0", "", t.result + " = new " + t.arg1, t.line);
                break;
            }
            case TACOp::FREE:
                emitComment("free: " + t.toString(), t.line);
                emit(AsmOp::NOP, "", "", "", "delete " + t.arg1, t.line);
                break;
            case TACOp::THROW:
                emitComment("throw: " + t.toString(), t.line);
                emit(AsmOp::NOP, "", "", "", "throw " + t.arg1, t.line);
                break;
            case TACOp::ADDR_OF: {
                Reg r = allocReg(t.result);
                emit(AsmOp::MOV, regName(r), "#0", "", t.result + " = &" + t.arg1, t.line);
                break;
            }
            case TACOp::DEREF: {
                Reg r = allocReg(t.result);
                emit(AsmOp::MOV, regName(r), "#0", "", t.result + " = *" + t.arg1, t.line);
                break;
            }
            case TACOp::CAST: {
                Reg r = allocReg(t.result);
                std::string src = loadOperand(t.arg1, t.line);
                emit(AsmOp::MOV, regName(r), src, "", t.result + " = (" + t.arg2 + ")" + t.arg1, t.line);
                break;
            }

            default:
                emitComment("skipped: " + t.toString(), t.line);
                break;
        }
    }
}

// ══════════════════════════════════════════════════════════
//  TAC → Assembly translators
// ══════════════════════════════════════════════════════════

void CodeGenerator::genFuncBegin(const TACInstr& t) {
    emitComment("─── function: " + t.result + " ───", t.line);
    emit(AsmOp::FUNC_BEGIN, t.result, "", "",
         "prologue", t.line);
    // Reset register map for new function scope
    regMap_.clear();
    regUser_.clear();
    for (int i = 0; i < 8; i++) regFree_[i] = true;
    memOffset_ = 0;
}

void CodeGenerator::genFuncEnd(const TACInstr& t) {
    // Implicit safety-net RET: void functions have no explicit return statement,
    // so without this they fall through FUNC_END into the next function → infinite loop.
    // For functions with an explicit return, this RET is unreachable dead code (harmless).
    emit(AsmOp::RET, "", "", "", "implicit return", t.line);
    emit(AsmOp::FUNC_END, t.result, "", "", "epilogue", t.line);
    emitComment("─── end: " + t.result + " ───", t.line);
}

void CodeGenerator::genAssign(const TACInstr& t) {
    // result = arg1
    std::string src = loadOperand(t.arg1, t.line);
    Reg dstReg = allocReg(t.result);

    emitComment(t.result + " = " + t.arg1, t.line);
    emit(AsmOp::MOV, regName(dstReg), src, "",
         t.result + " = " + t.arg1, t.line);
}

void CodeGenerator::genBinaryOp(const TACInstr& t) {
    // result = arg1 op arg2
    std::string s1 = loadOperand(t.arg1, t.line);
    std::string s2 = loadOperand(t.arg2, t.line);

    Reg dstReg = allocReg(t.result);

    emitComment(t.toString(), t.line);

    AsmOp aop = AsmOp::NOP;
    AsmOp setOp = AsmOp::NOP;

    switch (t.op) {
        case TACOp::ADD:     aop = AsmOp::ADD;  break;
        case TACOp::SUB:     aop = AsmOp::SUB;  break;
        case TACOp::MUL:     aop = AsmOp::MUL;  break;
        case TACOp::DIV:     aop = AsmOp::DIV;  break;
        case TACOp::MOD:     aop = AsmOp::MOD;  break;
        case TACOp::BIT_AND: aop = AsmOp::AND;  break;
        case TACOp::BIT_OR:  aop = AsmOp::OR;   break;
        case TACOp::BIT_XOR: aop = AsmOp::XOR;  break;
        case TACOp::AND:     aop = AsmOp::AND;  break;
        case TACOp::OR:      aop = AsmOp::OR;   break;
        case TACOp::LSHIFT:  aop = AsmOp::SHL;  break;
        case TACOp::RSHIFT:  aop = AsmOp::SHR;  break;

        // Comparison: CMP + SET
        case TACOp::EQ:
            emit(AsmOp::CMP, "", s1, s2, "compare", t.line);
            emit(AsmOp::SETE,  regName(dstReg), "", "", "set if equal", t.line);
            return;
        case TACOp::NEQ:
            emit(AsmOp::CMP, "", s1, s2, "compare", t.line);
            emit(AsmOp::SETNE, regName(dstReg), "", "", "set if not equal", t.line);
            return;
        case TACOp::LT:
            emit(AsmOp::CMP, "", s1, s2, "compare", t.line);
            emit(AsmOp::SETL,  regName(dstReg), "", "", "set if less", t.line);
            return;
        case TACOp::GT:
            emit(AsmOp::CMP, "", s1, s2, "compare", t.line);
            emit(AsmOp::SETG,  regName(dstReg), "", "", "set if greater", t.line);
            return;
        case TACOp::LTE:
            emit(AsmOp::CMP, "", s1, s2, "compare", t.line);
            emit(AsmOp::SETLE, regName(dstReg), "", "", "set if less/equal", t.line);
            return;
        case TACOp::GTE:
            emit(AsmOp::CMP, "", s1, s2, "compare", t.line);
            emit(AsmOp::SETGE, regName(dstReg), "", "", "set if greater/equal", t.line);
            return;

        default:
            aop = AsmOp::ADD;
    }

    emit(aop, regName(dstReg), s1, s2,
         t.toString(), t.line);
}

void CodeGenerator::genUnaryOp(const TACInstr& t) {
    std::string src = loadOperand(t.arg1, t.line);
    Reg dstReg = allocReg(t.result);

    emitComment(t.toString(), t.line);

    if (t.op == TACOp::NOT || t.op == TACOp::BIT_NOT) {
        emit(AsmOp::NOT, regName(dstReg), src, "",
             t.toString(), t.line);
    } else {
        emit(AsmOp::NEG, regName(dstReg), src, "",
             t.toString(), t.line);
    }
}

void CodeGenerator::genJump(const TACInstr& t) {
    emit(AsmOp::JMP, t.arg1, "", "",
         "goto " + t.arg1, t.line);
}

void CodeGenerator::genJumpIf(const TACInstr& t) {
    // if cond goto label
    std::string cond = loadOperand(t.arg1, t.line);
    emit(AsmOp::CMP,  "", cond, "#0", "test condition", t.line);
    emit(AsmOp::JNZ,  t.arg2, "", "",
         "jump if true to " + t.arg2, t.line);
}

void CodeGenerator::genJumpIfNot(const TACInstr& t) {
    // ifnot cond goto label
    std::string cond = loadOperand(t.arg1, t.line);
    emit(AsmOp::CMP, "", cond, "#0", "test condition", t.line);
    emit(AsmOp::JZ,  t.arg2, "", "",
         "jump if false to " + t.arg2, t.line);
}

void CodeGenerator::genLabel(const TACInstr& t) {
    emit(AsmOp::LABEL, t.result, "", "",
         "", t.line);
}

void CodeGenerator::genCall(const TACInstr& t) {
    // Strip object prefix from method calls: "p.getX" → "getX", "p->foo" → "foo"
    // TAC arg1 keeps the full "p.getX" form (educational); assembly CALL uses bare name
    std::string funcLabel = t.arg1;
    size_t arrow = funcLabel.rfind("->");
    if (arrow != std::string::npos)
        funcLabel = funcLabel.substr(arrow + 2);
    else {
        size_t dot = funcLabel.rfind('.');
        if (dot != std::string::npos)
            funcLabel = funcLabel.substr(dot + 1);
    }

    int argCount = 0;
    try { argCount = std::stoi(t.arg2); } catch (...) {}

    std::vector<AsmInstr> argPushes;
    for (int i = 0; i < argCount && !instrs_.empty(); i++) {
        const AsmInstr& last = instrs_.back();
        if (last.op != AsmOp::PUSH) break;
        argPushes.push_back(last);
        instrs_.pop_back();
    }
    std::reverse(argPushes.begin(), argPushes.end());

    std::vector<Reg> savedRegs;
    for (const auto& entry : regUser_) {
        Reg r = entry.first;
        if (r == Reg::R0 || r == Reg::NONE) continue;
        savedRegs.push_back(r);
        emit(AsmOp::PUSH, regName(r), "", "",
             "save caller " + regName(r), t.line);
    }

    for (const auto& arg : argPushes) {
        emit(AsmOp::PUSH, arg.dst, arg.src1, arg.src2,
             arg.comment, arg.tacId);
    }

    emitComment("call " + t.arg1, t.line);
    emit(AsmOp::CALL, funcLabel, "", "",
         "call function " + t.arg1, t.line);

    for (auto it = savedRegs.rbegin(); it != savedRegs.rend(); ++it) {
        emit(AsmOp::POP, regName(*it), "", "",
             "restore caller " + regName(*it), t.line);
    }

    // Store return value
    if (!t.result.empty()) {
        Reg dstReg = allocReg(t.result);
        // Return value is in R0 by convention
        emit(AsmOp::MOV, regName(dstReg), "R0", "",
             t.result + " = return value", t.line);
    }
}

void CodeGenerator::genReturn(const TACInstr& t) {
    if (!t.arg1.empty()) {
        std::string src = loadOperand(t.arg1, t.line);
        // Move return value to R0 by convention
        emit(AsmOp::MOV, "R0", src, "",
             "return value → R0", t.line);
    }
    emit(AsmOp::RET, "", "", "",
         "return", t.line);
}

void CodeGenerator::genParam(const TACInstr& t) {
    if (!t.result.empty()) {
        // Function parameter declaration: pop argument from the call stack into
        // the parameter register. The parameters are emitted in reverse order
        // so the first declared parameter receives the first pushed argument.
        Reg dstReg = allocReg(t.result);
        emit(AsmOp::POP, regName(dstReg), "", "",
             "pop param " + t.result, t.line);
        return;
    }

    std::string src = loadOperand(t.arg1, t.line);
    emit(AsmOp::PUSH, src, "", "",
         "push param " + t.arg1, t.line);
}

void CodeGenerator::genPrint(const TACInstr& t) {
    // arg1 mein print karne wali value hai
    std::string val = t.arg1;

    // String literal — directly PRINT karo, register mein mat daalo
    if (!val.empty() && val[0] == '"') {
        emit(AsmOp::PRINT, val, "", "",
             "print string " + val, t.line);
        return;
    }

    // Newline
    if (val == "\\n" || val == "\n") {
        emit(AsmOp::PRINT, "\\n", "", "",
             "print newline", t.line);
        return;
    }

    // Variable ya number — register mein load karo
    std::string src = loadOperand(val, t.line);
    emit(AsmOp::PRINT, src, "", "",
         "print " + val, t.line);
}

void CodeGenerator::genRead(const TACInstr& t) {
    // READ into a register for cin >> target
    Reg dstReg = allocReg(t.result);
    emit(AsmOp::READ, regName(dstReg), "", "",
         "read " + t.result, t.line);
}

// ══════════════════════════════════════════════════════════
//  JSON escape
// ══════════════════════════════════════════════════════════

std::string CodeGenerator::escapeJSON(const std::string& s) const {
    std::string out;
    for (char c : s) {
        switch (c) {
            case '"':  out += "\\\""; break;
            case '\\': out += "\\\\"; break;
            case '\n': out += "\\n";  break;
            case '\r': out += "\\r";  break;
            case '\t': out += "\\t";  break;
            default:   out += c;
        }
    }
    return out;
}

// ══════════════════════════════════════════════════════════
//  Assembly listing (human readable)
// ══════════════════════════════════════════════════════════

std::string CodeGenerator::toListing() const {
    std::ostringstream out;
    out << "; Metamic VRM Assembly\n";
    out << "; Generated by Visual Educational Compiler\n\n";
    for (const auto& instr : instrs_) {
        out << instr.toString() << "\n";
    }
    return out.str();
}

// ══════════════════════════════════════════════════════════
//  JSON output
// ══════════════════════════════════════════════════════════

std::string CodeGenerator::toJSON() const {
    std::ostringstream out;
    out << "[\n";
    for (size_t i = 0; i < instrs_.size(); i++) {
        out << "    " << instrs_[i].toJSON();
        if (i + 1 < instrs_.size()) out << ",";
        out << "\n";
    }
    out << "  ]";
    return out.str();
}
